# Generated by Django 5.1.2 on 2024-11-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_category_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('chair', 'Chair'), ('table', 'Table')], default='chair', max_length=50),
        ),
    ]
