# Generated by Django 5.1.2 on 2024-11-16 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ordered', 'Ordered')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 21, 16, 46, 20, 192513, tzinfo=datetime.timezone.utc)),
        ),
    ]
