# Generated by Django 5.1.2 on 2024-12-17 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cart_status_alter_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 22, 17, 44, 26, 351307, tzinfo=datetime.timezone.utc)),
        ),
    ]
